import RPi.GPIO as GPIO
import time

BUTTON_GPIO_UP = 22
BUTTON_GPIO_DOWN = 27
BUTTON_GPIO_ENTER = 22

GPIO.setmode(GPIO.BCM)
GPIO.setup(BUTTON_GPIO_UP, GPIO.OUT)
GPIO.setup(BUTTON_GPIO_DOWN, GPIO.OUT)

# Default = buttons not pressed
GPIO.output(BUTTON_GPIO_UP, GPIO.LOW)
GPIO.output(BUTTON_GPIO_DOWN, GPIO.LOW)

# Simulate a press
GPIO.output(BUTTON_GPIO_UP, GPIO.HIGH)
GPIO.output(BUTTON_GPIO_DOWN, GPIO.HIGH)
time.sleep(3)  # hold for 200ms
GPIO.output(BUTTON_GPIO_UP, GPIO.LOW)
GPIO.output(BUTTON_GPIO_DOWN, GPIO.LOW)
GPIO.cleanup()